### ISSUE TITLE
Episode 01: Assessing Read Quality Changes

### ISSUE THREAD

**Issue by fpsom** [data-lessons/wrangling-genomics#1]
Edit for [Episode 01](https://github.com/taylorreiter/wrangling-genomics/blob/gh-pages/_episodes/00-quality-control.md): Assessing Read Quality
- [x] Download data that will be used for this pipeline using `curl`. Full fastq files will be downloaded from the ENA. Subsampled fastq files will be created and posted on figshare for download.
- [x] Add use of `scp` (which will be introduced during Shell Genomics on Day 1) to transfer fastqc html files. Consider using cyberduck / filezilla as a backup tranfser method.
- [x] Mention the other features of `fastqc`, in that it searches for sequencing adapter content and can report this. Over-represented sequences plot could also be diagnostic of the sequencing library. See [Issue #118 of original repo](https://github.com/datacarpentry/wrangling-genomics/issues/118). 
- [x] Moving hidden files is confusing - this will not be addressed, as it will be redundant in the new structure. See also [Issue #112 of main repo](https://github.com/datacarpentry/wrangling-genomics/issues/112).

**Comment by taylorreiter** [comment]
files are currently on osf, but can be moved to figshare. I saw this link for other DC genomics files on osf, so osf might also be their final resting place https://osf.io/ycu8j/

**Comment by taylorreiter** [comment]
Also note that scp might need to be added to current shell genomics to accommodate its use in these episodes.

Lastly, we will have hidden files on the instance in a `.backup` folder in case long downloads fail or files are accidentally deleted.
