### ISSUE TITLE
instructor notes are missing

### ISSUE THREAD

**Issue by raynamharris** [data-lessons/wrangling-genomics#16]
The `_extras/guide.md` is only a placeholder with "FIXME". It needs updating. Should include notes for each episode.

- [x] 0 Assessing Read Quality
- [x] 1 Trimming and Filtering
- [x] 2 Variant Calling Workflow
- [ ] 3 Automating a Variant Calling Workflow

**Comment by raynamharris** [comment]
Yea! Thanks to @jessicamizzi the instructor guide now includes notes for episodes 0-2.

**Comment by taylorreiter** [comment]
@jessicamizzi with #22 I think 03-automation will be stable. Would you be willing to add instructor notes for this episode as well?

**Comment by jessicamizzi** [comment]
@taylorreiter sure! I can work on it tomorrow

**Comment by taylorreiter** [comment]
addressed in #28!
