### ISSUE TITLE
Reason for this fork is not explained

### ISSUE THREAD

**Issue by peterjc** [data-lessons/wrangling-genomics#17]
Could the (one line) repository description metadata on GitHub explain the purpose of this fork from https://github.com/datacarpentry/wrangling-genomics please?

Likewise it would be good to explain what the GitHub organisation https://github.com/data-lessons is.

**Comment by ErinBecker** [comment]
Thank you @peterjc for this issue. The data-lessons forks were created for early stage re-development of the datacarpentry genomics lessons, so as not to break anything in the repositories that were being used for live teaching. These forks are no longer active. They need to be checked to ensure that all updates are merged back into the datacarpentry repos and then deleted.

**Comment by peterjc** [comment]
Thank you, I think the new description for the repository resolves this:

*Deprecated - this repository is an outdated fork from datacarpentry/wrangling-genomics.*
