### ISSUE TITLE
Episode 02: Trimming and Filtering Changes

### ISSUE THREAD

**Issue by fpsom** [data-lessons/wrangling-genomics#2]
Edit for [Episode 02](https://github.com/taylorreiter/wrangling-genomics/blob/gh-pages/_episodes/01-trimming.md)
- [x] Add a section to show the Trimmomatic manual.
- [ ] Review trimming parameters. See also [Issue #113 of original repo](https://github.com/datacarpentry/wrangling-genomics/issues/113)

**Comment by crazyhottommy** [comment]
let me work on this now. thx for putting everything up.

**Comment by taylorreiter** [comment]
@crazyhottommy have you made any progress on this? 

I'm not sure it's the best idea to change the trimming parameters. I think we should add a discussion about what different trimming parameters mean and when it might be appropriate to relax these parameters though. Here's a [study](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0085024) that tested trimming on different data sets.

**Comment by crazyhottommy** [comment]
did not have time to respond to this, but we talked yesterday and you can work on this. thx!

**Comment by taylorreiter** [comment]
I'm weary of adding a discussion on trimming parameters right now as the lesson may become too long. I am closing this issue and this discussion can always be restarted later if others have strong feelings about it.
