### ISSUE TITLE
Episode 04: Automating a Variant Calling Workflow Changes

### ISSUE THREAD

**Issue by fpsom** [data-lessons/wrangling-genomics#4]
Edits for [Episode 04](https://github.com/taylorreiter/wrangling-genomics/blob/gh-pages/_episodes/03-automation.md): Automating a Variant Calling Workflow
- [x] Only live code the “Automating QCing” section. Revise to include variables and arguments, which will be covered in Shell Genomics Day 1.
- [x] Remove the final script **or** have it as an optional exercise (script revised to reflect a _core_ script that is being called by another)
- [x] Add set -e to Automating a Variant Calling Workflow shell script. See [Issue #122 of main repo](https://github.com/datacarpentry/wrangling-genomics/issues/122)
- [x] Need to prep learners for `basename` in the automation lesson - this is not going to be addressed, as it will be dropped by the new setup. See [Issue #117 of main repo](https://github.com/datacarpentry/wrangling-genomics/issues/117)

**Comment by taylorreiter** [comment]
@fpsom @shannonekj @bluegenes should we add `set -e` to the beginning of the two shell scripts in [03-automation](https://github.com/data-lessons/wrangling-genomics/blob/gh-pages/_episodes/03-automation.md)? Second file used in lesson is [here](https://github.com/data-lessons/wrangling-genomics/blob/gh-pages/files/run_variant_calling.sh).

**Comment by shannonekj** [comment]
I'm pro changing the files so when learners come back to the lesson they are physically reminded of the good practice.
