### ISSUE TITLE
check that contributor guidelines are clear and consistent

### ISSUE THREAD

**Issue by NielInfante** [data-lessons/wrangling-genomics#5]

**Comment by HadrienG** [comment]
Example of contributor guidelines from the sw-carpentry Unix lesson [here](https://github.com/swcarpentry/shell-novice/blob/gh-pages/CONTRIBUTING.md)

And from the data carpentry ecology lessons [here](https://github.com/datacarpentry/spreadsheet-ecology-lesson/blob/gh-pages/CONTRIBUTING.md)

TODO:

- [ ] make a diff of both
- [ ] adapt it if needed 
- [ ] fix link to work on wrangling genomics pages

**Comment by ErinBecker** [comment]
Best to use data carpentry ecology lessons as an example here. These were revised most recently and should be most up to date. Data Carpentry and Software Carpentry will be somewhat different.

**Comment by HadrienG** [comment]
Thanks Erin! 

The contributor guidelines seemed up-to-date, just a few links to change 🎉

**Comment by HadrienG** [comment]
Closed with 0e53b2c
